### Get all clients
GET localhost:8080/myUser

### Get myUser by id
GET localhost:8080/myUser/2

### Create a new myUser
POST localhost:8080/myUser
Content-Type: application/json

{
  "name": "Josi Ribeiro",
  "email": "josi@josi.com",
  "age": "AGE_OVER_50",
  "skinTypeClient": "DRY",
  "howMuch": "$$$",
  "pigmentedSkin":"YES",
  "sensitiveSkin": "NO"

}

### delet a myUser
DELETE localhost:8080/myUser/4

### Add a routine to a myUser
POST localhost:8080/myUser/1/routine
Content-Type: application/json

{
  "name": "Maria`s Routine"
}

