### Get all Products
GET localhost:8080/products

### Get Products by id
GET localhost:8080/products/13

### Create a new Product
POST localhost:8080/products
Content-Type: application/json

{
  "name": "Watermelon Glow Niacinamide Dew Drops",
  "company": "Glow Recipe",
  "price": 35.00
}

### delet a product
DELETE localhost:8080/products/16

### Add a Category to a Product
POST localhost:8080/products/26/categories
Content-Type: application/json

{
  "name": "serum"
}

### Add a skinType to a Product
POST localhost:8080/products/26/skinTypes
Content-Type: application/json

{
  "name": "all"
}

### Add a feature to a Product
POST localhost:8080/products/26/feature
Content-Type: application/json

{
  "name": "anti pigmentation"
}

### Add a step to a Product
POST localhost:8080/products/15/step
Content-Type: application/json

{
  "name": "tonic"
}




### find category from the product
GET localhost:8080/products/categories/moisturizer
Content-Type: application/json