### Get all Products
GET localhost:8080/products


### Get Products by id
GET localhost:8080/products/12

### delet a product
DELETE localhost:8080/products/41


### Create a new Product
POST localhost:8080/products
Content-Type: application/json

{
  "name": "Cleasing Oil and Mask",
  "company": "Frei Öl",
  "price": 18.60,
  "skinTypes": [
  ],
  "features": [],
  "categories": [],
  "steps": []
}

### update a Product
PUT localhost:8080/products/42
Content-Type: application/json

{
  "name": "Cleasing Oil and Mask",
  "company": "Frei Öl",
  "price": 18.60
}
### Add a Category to a Product
POST localhost:8080/products/42/categories
Content-Type: application/json

{
  "idCategory": 5,
  "name": "TWICE A WEEK"
}

### Add a skinType to a Product
POST localhost:8080/products/42/skinTypes
Content-Type: application/json

{
  "idCategory": 5,
  "name": "DRY"
}

### Add a feature to a Product
POST localhost:8080/products/42/features
Content-Type: application/json

{
  "idCategory": 0,
  "name": "SENSITIVE SKIN"
}

### Add a step to a Product
##POST localhost:8080/product/15/step
##Content-Type: application/json



